<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admins = [
            [
                'name' => 'Pashupati Sah',
                'first_name' => 'Pashupati',
                'middle_name' => '',
                'last_name' => 'Sah',
                'username' => 'pashupati35',
                'email' => 'pashupatisah35@gmail.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841234567',
                'mobile' => '+977-9841234567',
                'phone' => '+977-1-4455667',
                'address' => 'Kathmandu, Bagmati, Nepal',
                'designation' => 'Super Administrator & Fleet Director',
                'position' => 'Chief Executive',
                'gender' => 'male',
                'marital_status' => 'single',
                'nationality' => 'Nepali',
                'citizenship_number' => '27-01-76-12345',
                'passport_number' => 'N1234567',
                'user_type' => 'super_admin',
                'access_type' => 'full_access',
                'has_email_access' => true,
                'approval_status' => 'approved',
                'is_submitted' => true,
                'theme_style' => 'light',
            ],
            [
                'name' => 'Pashupati Sah (Backup)',
                'first_name' => 'Pashupati',
                'middle_name' => '',
                'last_name' => 'Sah',
                'username' => 'pashupatisah',
                'email' => 'pashupatisah@gmail.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9801234567',
                'mobile' => '+977-9801234567',
                'address' => 'Lalitpur, Nepal',
                'designation' => 'Senior Administrator',
                'position' => 'Head of Operations',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'super_admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Main Admin',
                'first_name' => 'System',
                'last_name' => 'Admin',
                'username' => 'sysadmin',
                'email' => 'admin@example.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9811122334',
                'mobile' => '+977-9811122334',
                'address' => 'Bhaktapur, Nepal',
                'designation' => 'System Administrator',
                'position' => 'IT Lead',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Aarav Sharma',
                'first_name' => 'Aarav',
                'last_name' => 'Sharma',
                'username' => 'aarav_ops',
                'email' => 'aarav.sharma@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000001',
                'mobile' => '+977-9841000001',
                'address' => 'Baneshwor, Kathmandu',
                'designation' => 'Fleet Operations Manager',
                'position' => 'Operations Manager',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Sunita Shrestha',
                'first_name' => 'Sunita',
                'last_name' => 'Shrestha',
                'username' => 'sunita_support',
                'email' => 'sunita.shrestha@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000002',
                'mobile' => '+977-9841000002',
                'address' => 'Patan Dhoka, Lalitpur',
                'designation' => 'Customer Relations Lead',
                'position' => 'Support Lead',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Bikash Adhikari',
                'first_name' => 'Bikash',
                'last_name' => 'Adhikari',
                'username' => 'bikash_finance',
                'email' => 'bikash.adhikari@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000003',
                'mobile' => '+977-9841000003',
                'address' => 'Thamel, Kathmandu',
                'designation' => 'Chief Financial Officer',
                'position' => 'Finance Head',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Puja Karki',
                'first_name' => 'Puja',
                'last_name' => 'Karki',
                'username' => 'puja_marketing',
                'email' => 'puja.karki@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000004',
                'mobile' => '+977-9841000004',
                'address' => 'Jhamsikhel, Lalitpur',
                'designation' => 'Digital Marketing Lead',
                'position' => 'Marketing Head',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Rohan Gurung',
                'first_name' => 'Rohan',
                'last_name' => 'Gurung',
                'username' => 'rohan_dispatch',
                'email' => 'rohan.gurung@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000005',
                'mobile' => '+977-9841000005',
                'address' => 'Pokhara, Gandaki',
                'designation' => 'Regional Dispatch Manager',
                'position' => 'Branch Manager',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Manish Thapa',
                'first_name' => 'Manish',
                'last_name' => 'Thapa',
                'username' => 'manish_audit',
                'email' => 'manish.thapa@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000006',
                'mobile' => '+977-9841000006',
                'address' => 'Chitwan, Bagmati',
                'designation' => 'Compliance & Safety Auditor',
                'position' => 'Safety Officer',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Anjali Joshi',
                'first_name' => 'Anjali',
                'last_name' => 'Joshi',
                'username' => 'anjali_hr',
                'email' => 'anjali.joshi@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000007',
                'mobile' => '+977-9841000007',
                'address' => 'Biratnagar, Koshi',
                'designation' => 'HR & Talent Acquisition Lead',
                'position' => 'HR Manager',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Deepak KC',
                'first_name' => 'Deepak',
                'last_name' => 'KC',
                'username' => 'deepak_dev',
                'email' => 'deepak.kc@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000008',
                'mobile' => '+977-9841000008',
                'address' => 'Butwal, Lumbini',
                'designation' => 'Technical Support Specialist',
                'position' => 'IT Specialist',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Nisha Tamang',
                'first_name' => 'Nisha',
                'last_name' => 'Tamang',
                'username' => 'nisha_billing',
                'email' => 'nisha.tamang@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000009',
                'mobile' => '+977-9841000009',
                'address' => 'Hetauda, Bagmati',
                'designation' => 'Billing & Invoicing Manager',
                'position' => 'Accounts Officer',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Sanjay Mahato',
                'first_name' => 'Sanjay',
                'last_name' => 'Mahato',
                'username' => 'sanjay_quality',
                'email' => 'sanjay.mahato@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000010',
                'mobile' => '+977-9841000010',
                'address' => 'Janakpur, Madhesh',
                'designation' => 'Quality Assurance Manager',
                'position' => 'QA Officer',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Rashmi Poudel',
                'first_name' => 'Rashmi',
                'last_name' => 'Poudel',
                'username' => 'rashmi_reservations',
                'email' => 'rashmi.poudel@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000011',
                'mobile' => '+977-9841000011',
                'address' => 'Dharan, Koshi',
                'designation' => 'Reservations Supervisor',
                'position' => 'Booking Coordinator',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Bibek Dahal',
                'first_name' => 'Bibek',
                'last_name' => 'Dahal',
                'username' => 'bibek_logistics',
                'email' => 'bibek.dahal@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000012',
                'mobile' => '+977-9841000012',
                'address' => 'Bhadrapur, Jhapa',
                'designation' => 'Fleet Logistics Officer',
                'position' => 'Logistics Officer',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Sita Gautam',
                'first_name' => 'Sita',
                'last_name' => 'Gautam',
                'username' => 'sita_clientcare',
                'email' => 'sita.gautam@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000013',
                'mobile' => '+977-9841000013',
                'address' => 'Gorkha, Gandaki',
                'designation' => 'Client Care Executive',
                'position' => 'Customer Care',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Kiran Basnet',
                'first_name' => 'Kiran',
                'last_name' => 'Basnet',
                'username' => 'kiran_fleetsec',
                'email' => 'kiran.basnet@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000014',
                'mobile' => '+977-9841000014',
                'address' => 'Nepalgunj, Lumbini',
                'designation' => 'Security & Telematics Lead',
                'position' => 'Security Officer',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Karuna Rai',
                'first_name' => 'Karuna',
                'last_name' => 'Rai',
                'username' => 'karuna_partners',
                'email' => 'karuna.rai@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000015',
                'mobile' => '+977-9841000015',
                'address' => 'Ilam, Koshi',
                'designation' => 'Partner Relations Manager',
                'position' => 'Vendor Relations',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Prakash Yadav',
                'first_name' => 'Prakash',
                'last_name' => 'Yadav',
                'username' => 'prakash_maint',
                'email' => 'prakash.yadav@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000016',
                'mobile' => '+977-9841000016',
                'address' => 'Birgunj, Parsa',
                'designation' => 'Vehicle Maintenance Supervisor',
                'position' => 'Maintenance Lead',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
            [
                'name' => 'Samir Bista',
                'first_name' => 'Samir',
                'last_name' => 'Bista',
                'username' => 'samir_legal',
                'email' => 'samir.bista@carrental.com',
                'password' => Hash::make('password'),
                'contact_number' => '+977-9841000017',
                'mobile' => '+977-9841000017',
                'address' => 'Dhangadhi, Sudurpashchim',
                'designation' => 'Legal & Compliance Officer',
                'position' => 'Legal Counsel',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'user_type' => 'admin',
                'approval_status' => 'approved',
            ],
        ];

        foreach ($admins as $index => $data) {
            $data['unique_identifier'] = 'ADM-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);
            $data['theme_style'] = $data['theme_style'] ?? 'light';
            $data['approval_status'] = $data['approval_status'] ?? 'approved';
            $data['is_submitted'] = $data['is_submitted'] ?? true;
            $data['has_email_access'] = $data['has_email_access'] ?? true;
            
            Admin::updateOrCreate(['email' => $data['email']], $data);
        }
    }
}
