<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Owner;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class OwnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $primaryAdmin = Admin::first();
        $adminId = $primaryAdmin ? $primaryAdmin->id : 1;

        $owners = [
            [
                'full_name' => 'Rajesh Sharma',
                'first_name' => 'Rajesh',
                'last_name' => 'Sharma',
                'email' => 'owner@futech.com',
                'contact_number' => '+977-9841234567',
                'mobile' => '+977-9841234567',
                'address' => 'Kathmandu, Bagmati, Nepal',
                'gender' => 'male',
                'marital_status' => 'married',
                'nationality' => 'Nepali',
                'citizenship_number' => '27-01-70-11223',
                'designation' => 'Fleet Enterprise Owner',
                'user_type' => 'owner',
                'approval_status' => 'approved',
                'register_type' => 'admin_created',
            ],
            [
                'full_name' => 'Binod Chaudhary',
                'first_name' => 'Binod',
                'last_name' => 'Chaudhary',
                'email' => 'binod.chaudhary@himalayanfleet.com',
                'contact_number' => '+977-9851023456',
                'mobile' => '+977-9851023456',
                'address' => 'Lalitpur, Nepal',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Himalayan Fleet Logistics',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Sujata Koirala',
                'first_name' => 'Sujata',
                'last_name' => 'Koirala',
                'email' => 'sujata.koirala@everestcars.com',
                'contact_number' => '+977-9851034567',
                'mobile' => '+977-9851034567',
                'address' => 'Pokhara, Gandaki, Nepal',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Everest Luxury Cars',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Kishore Baniya',
                'first_name' => 'Kishore',
                'last_name' => 'Baniya',
                'email' => 'kishore.baniya@pokhararentals.com',
                'contact_number' => '+977-9851045678',
                'mobile' => '+977-9851045678',
                'address' => 'Lakeside, Pokhara',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Pokhara Car Hub',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Pratima Shrestha',
                'first_name' => 'Pratima',
                'last_name' => 'Shrestha',
                'email' => 'pratima.shrestha@kathmanducars.com',
                'contact_number' => '+977-9851056789',
                'mobile' => '+977-9851056789',
                'address' => 'Durbar Marg, Kathmandu',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Capital City Fleet',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Gopal Krishna श्रेष्ठ',
                'first_name' => 'Gopal Krishna',
                'last_name' => 'Shrestha',
                'email' => 'gopal.shrestha@royalrides.np',
                'contact_number' => '+977-9851067890',
                'mobile' => '+977-9851067890',
                'address' => 'Bhaktapur, Nepal',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Royal Rides Nepal',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Anil Thapa',
                'first_name' => 'Anil',
                'last_name' => 'Thapa',
                'email' => 'anil.thapa@annapurnafleet.com',
                'contact_number' => '+977-9851078901',
                'mobile' => '+977-9851078901',
                'address' => 'Chitwan, Nepal',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Annapurna Safari Rides',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Mina Tamang',
                'first_name' => 'Mina',
                'last_name' => 'Tamang',
                'email' => 'mina.tamang@mountainwheels.com',
                'contact_number' => '+977-9851089012',
                'mobile' => '+977-9851089012',
                'address' => 'Nagarkot, Bhaktapur',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Mountain Wheels Co.',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Sunil Basnet',
                'first_name' => 'Sunil',
                'last_name' => 'Basnet',
                'email' => 'sunil.basnet@lumbinirentals.com',
                'contact_number' => '+977-9851090123',
                'mobile' => '+977-9851090123',
                'address' => 'Butwal, Lumbini',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Lumbini Express Cars',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Devendra Shah',
                'first_name' => 'Devendra',
                'last_name' => 'Shah',
                'email' => 'devendra.shah@nepalpremiertours.com',
                'contact_number' => '+977-9851101234',
                'mobile' => '+977-9851101234',
                'address' => 'Baluwatar, Kathmandu',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Premier Tours & Cars',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Rita Pant',
                'first_name' => 'Rita',
                'last_name' => 'Pant',
                'email' => 'rita.pant@fasttrackcabs.com',
                'contact_number' => '+977-9851112345',
                'mobile' => '+977-9851112345',
                'address' => 'Dhangadhi, Nepal',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'FastTrack Mobility',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Bhuwan Karki',
                'first_name' => 'Bhuwan',
                'last_name' => 'Karki',
                'email' => 'bhuwan.karki@dharantransit.com',
                'contact_number' => '+977-9851123456',
                'mobile' => '+977-9851123456',
                'address' => 'Dharan, Koshi',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Eastern Motors',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Kamala Subedi',
                'first_name' => 'Kamala',
                'last_name' => 'Subedi',
                'email' => 'kamala.subedi@valleyrides.com',
                'contact_number' => '+977-9851134567',
                'mobile' => '+977-9851134567',
                'address' => 'Sanepa, Lalitpur',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Valley Express Fleet',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Hari Prasad Bhattarai',
                'first_name' => 'Hari',
                'last_name' => 'Bhattarai',
                'email' => 'hari.bhattarai@peacecabs.com',
                'contact_number' => '+977-9851145678',
                'mobile' => '+977-9851145678',
                'address' => 'Janakpur, Madhesh',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Mithila Travels & Fleet',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Deepa Gurung',
                'first_name' => 'Deepa',
                'last_name' => 'Gurung',
                'email' => 'deepa.gurung@gurungcars.com',
                'contact_number' => '+977-9851156789',
                'mobile' => '+977-9851156789',
                'address' => 'Biratnagar, Nepal',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Gurung Auto Rentals',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Nabin Gautam',
                'first_name' => 'Nabin',
                'last_name' => 'Gautam',
                'email' => 'nabin.gautam@gautamfleet.com',
                'contact_number' => '+977-9851167890',
                'mobile' => '+977-9851167890',
                'address' => 'Nepalgunj, Banke',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Western Star Motors',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Shobha Acharya',
                'first_name' => 'Shobha',
                'last_name' => 'Acharya',
                'email' => 'shobha.acharya@citycruiser.com',
                'contact_number' => '+977-9851178901',
                'mobile' => '+977-9851178901',
                'address' => 'Hetauda, Makwanpur',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'City Cruiser Nepal',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Lokendra Rawal',
                'first_name' => 'Lokendra',
                'last_name' => 'Rawal',
                'email' => 'lokendra.rawal@karnalimotors.com',
                'contact_number' => '+977-9851189012',
                'mobile' => '+977-9851189012',
                'address' => 'Surkhet, Karnali',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Karnali Overland Rentals',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Sarita Poudyal',
                'first_name' => 'Sarita',
                'last_name' => 'Poudyal',
                'email' => 'sarita.poudyal@skylinecars.com',
                'contact_number' => '+977-9851190123',
                'mobile' => '+977-9851190123',
                'address' => 'Kirtipur, Kathmandu',
                'gender' => 'female',
                'nationality' => 'Nepali',
                'designation' => 'Skyline Luxury Fleet',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
            [
                'full_name' => 'Rameshwar Mahaseth',
                'first_name' => 'Rameshwar',
                'last_name' => 'Mahaseth',
                'email' => 'rameshwar.mahaseth@teraimotors.com',
                'contact_number' => '+977-9851201234',
                'mobile' => '+977-9851201234',
                'address' => 'Birgunj, Parsa',
                'gender' => 'male',
                'nationality' => 'Nepali',
                'designation' => 'Terai Highway Fleet',
                'user_type' => 'owner',
                'approval_status' => 'approved',
            ],
        ];

        foreach ($owners as $index => $data) {
            $data['admin_id'] = $adminId;
            $data['password'] = Hash::make('password');
            $data['unique_identifier'] = 'OWN-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT);
            $data['theme_style'] = 'light';
            $data['approval_status'] = 'approved';
            $data['is_submitted'] = true;
            $data['has_email_access'] = true;

            Owner::updateOrCreate(['email' => $data['email']], $data);
        }
    }
}
