<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { router } from '@inertiajs/vue3'
import axios from 'axios'
import MessageBox from '@/components/MessageBox.vue'

const props = withDefaults(
  defineProps<{
    email: string
    password: string
    remember?: boolean
    authType?: 'totp' | 'email'
  }>(),
  {
    remember: false,
    authType: 'totp',
  },
)

const emit = defineEmits(['back'])

const verificationCode = ref('')
const loading = ref(false)
const resending = ref(false)
const errorMessage = ref('')
const successMessage = ref('')
const resendTimer = ref(0)
let timerInterval: any = null

const startTimer = (seconds = 60) => {
  resendTimer.value = seconds
  clearInterval(timerInterval)
  timerInterval = setInterval(() => {
    if (resendTimer.value > 0) {
      resendTimer.value--
    } else {
      clearInterval(timerInterval)
    }
  }, 1000)
}

onMounted(() => {
  if (props.authType === 'email') {
    startTimer(60)
  }
})

onUnmounted(() => {
  clearInterval(timerInterval)
})

const resendVerificationCode = async () => {
  if (resendTimer.value > 0 || resending.value) return

  resending.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    const res = await axios.post('/owner/mfa/resend-code', {
      email: props.email,
      password: props.password,
    })

    if (res.data.status === 'OK') {
      successMessage.value = res.data.message || 'Verification code resent successfully.'
      startTimer(60)
    } else {
      errorMessage.value = res.data.errors || 'Failed to resend code.'
    }
  } catch (err: any) {
    errorMessage.value = err.response?.data?.errors || err.response?.data?.message || 'Unable to resend code.'
  } finally {
    resending.value = false
  }
}

const verifyCode = async () => {
  if (!verificationCode.value || verificationCode.value.length < 6) {
    errorMessage.value = 'Please enter the full 6-digit code.'
    
    return
  }

  loading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    const res = await axios.post('/owner/mfa/verify-code', {
      email: props.email,
      password: props.password,
      verification_code: verificationCode.value,
      remember: props.remember,
    })

    if (res.data.status === 'OK') {
      router.visit(res.data.redirect || '/owner/dashboard')
    } else {
      errorMessage.value = res.data.errors || 'Verification failed.'
    }
  } catch (err: any) {
    errorMessage.value = err.response?.data?.errors || err.response?.data?.message || 'Invalid code.'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="space-y-5">
    <div class="text-center mb-4">
      <div
        class="w-14 h-14 mx-auto mb-3 rounded-2xl flex items-center justify-center text-2xl border shadow-inner"
        :class="props.authType === 'email' ? 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 border-emerald-100 dark:border-emerald-900/50' : 'bg-blue-50 dark:bg-blue-950/50 text-blue-600 dark:text-blue-400 border-blue-100 dark:border-blue-900/50'"
      >
        <i
          v-if="props.authType === 'email'"
          class="ri-mail-check-line text-2xl"
        />
        <i
          v-else
          class="ri-shield-keyhole-line text-2xl"
        />
      </div>

      <h3 class="font-extrabold text-lg text-slate-900 dark:text-white">
        {{ props.authType === 'email' ? 'Owner Email Verification' : 'Owner Two-Factor Verification' }}
      </h3>
      <p class="text-xs text-slate-500 mt-1 max-w-xs mx-auto leading-relaxed">
        <template v-if="props.authType === 'email'">
          A 6-digit verification code has been sent to your registered owner email:
          <strong class="text-slate-800 dark:text-slate-200 block truncate mt-0.5">{{ props.email }}</strong>
        </template>
        <template v-else>
          Enter the 6-digit verification code generated by your Authenticator app (Google Authenticator, Microsoft Authenticator, etc.).
        </template>
      </p>
    </div>

    <!-- Alert Messages -->
    <MessageBox
      v-if="successMessage"
      :message="successMessage"
      type="success"
      @close="successMessage = ''"
    />

    <MessageBox
      v-if="errorMessage"
      :message="errorMessage"
      type="error"
      @close="errorMessage = ''"
    />

    <!-- Verification Code Input -->
    <div>
      <label class="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5 text-center">
        Enter 6-Digit Code
      </label>
      <input
        v-model="verificationCode"
        type="text"
        maxlength="6"
        placeholder="000000"
        autofocus
        class="w-full text-center tracking-[0.4em] text-2xl font-mono py-3 px-4 rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:ring-2 focus:ring-emerald-500 focus:outline-none shadow-inner transition-all"
        @keyup.enter="verifyCode"
      >
    </div>

    <!-- Action Buttons -->
    <div class="space-y-2.5">
      <button
        type="button"
        class="w-full py-3 px-4 rounded-2xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-bold text-xs shadow-lg shadow-emerald-600/25 transition-all flex items-center justify-center gap-2 cursor-pointer"
        :disabled="loading"
        @click="verifyCode"
      >
        <i
          v-if="loading"
          class="ri-loader-4-line animate-spin text-sm"
        />
        <span>{{ loading ? 'Verifying Code...' : 'Verify & Continue' }}</span>
      </button>

      <!-- Resend Code for Email Auth -->
      <div
        v-if="props.authType === 'email'"
        class="text-center pt-1"
      >
        <button
          type="button"
          class="text-xs font-bold transition-colors cursor-pointer"
          :class="resendTimer > 0 ? 'text-slate-400 cursor-not-allowed' : 'text-emerald-600 dark:text-emerald-400 hover:underline'"
          :disabled="resendTimer > 0 || resending"
          @click="resendVerificationCode"
        >
          <span v-if="resending">Sending code...</span>
          <span v-else-if="resendTimer > 0">Resend code in {{ resendTimer }}s</span>
          <span v-else>Didn't receive the code? Resend Code</span>
        </button>
      </div>

      <button
        type="button"
        class="w-full py-2.5 px-4 rounded-2xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-xs transition-colors cursor-pointer flex items-center justify-center gap-1.5"
        @click="emit('back')"
      >
        <i class="ri-arrow-left-line text-xs" />
        <span>Back to Login</span>
      </button>
    </div>
  </div>
</template>
