/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDatePicker: typeof import('./resources/ts/components/AppDatePicker.vue')['default']
    BookingLocationMap: typeof import('./resources/ts/components/BookingLocationMap.vue')['default']
    EventCalendar: typeof import('./resources/ts/components/EventCalendar.vue')['default']
    FormToggle: typeof import('./resources/ts/components/FormToggle.vue')['default']
    MessageBox: typeof import('./resources/ts/components/MessageBox.vue')['default']
    OtpInput: typeof import('./resources/ts/components/OtpInput.vue')['default']
    Pagination: typeof import('./resources/ts/components/Pagination.vue')['default']
    PasswordCheckList: typeof import('./resources/ts/components/PasswordCheckList.vue')['default']
    RichTextEditor: typeof import('./resources/ts/components/RichTextEditor.vue')['default']
    TableContent: typeof import('./resources/ts/components/table/components/table/TableContent.vue')['default']
    TableFooter: typeof import('./resources/ts/components/table/components/table/footer/TableFooter.vue')['default']
    ValidationError: typeof import('./resources/ts/components/ValidationError.vue')['default']
  }
}
