/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDatePicker: typeof import('./resources/ts/components/AppDatePicker.vue')['default']
    EventCalendar: typeof import('./resources/ts/components/EventCalendar.vue')['default']
    OtpInput: typeof import('./resources/ts/components/OtpInput.vue')['default']
    PasswordCheckList: typeof import('./resources/ts/components/PasswordCheckList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableContent: typeof import('./resources/ts/components/table/components/table/TableContent.vue')['default']
    TableFooter: typeof import('./resources/ts/components/table/components/table/footer/TableFooter.vue')['default']
    ValidationError: typeof import('./resources/ts/components/ValidationError.vue')['default']
  }
}
