/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDatePicker: typeof import('./resources/ts/components/AppDatePicker.vue')['default']
    EventCalendar: typeof import('./resources/ts/components/EventCalendar.vue')['default']
    FormToggle: typeof import('./resources/ts/components/FormToggle.vue')['default']
    MessageBox: typeof import('./resources/ts/components/MessageBox.vue')['default']
    OtpInput: typeof import('./resources/ts/components/OtpInput.vue')['default']
    Pagination: typeof import('./resources/ts/components/Pagination.vue')['default']
    PasswordCheckList: typeof import('./resources/ts/components/PasswordCheckList.vue')['default']
    RichTextEditor: typeof import('./resources/ts/components/RichTextEditor.vue')['default']
    TableContent: typeof import('./resources/ts/components/table/components/table/TableContent.vue')['default']
    TableFooter: typeof import('./resources/ts/components/table/components/table/footer/TableFooter.vue')['default']
    ValidationError: typeof import('./resources/ts/components/ValidationError.vue')['default']
  }
}

// For TSX support
declare global {
  const AppDatePicker: typeof import('./resources/ts/components/AppDatePicker.vue')['default']
  const EventCalendar: typeof import('./resources/ts/components/EventCalendar.vue')['default']
  const FormToggle: typeof import('./resources/ts/components/FormToggle.vue')['default']
  const MessageBox: typeof import('./resources/ts/components/MessageBox.vue')['default']
  const OtpInput: typeof import('./resources/ts/components/OtpInput.vue')['default']
  const Pagination: typeof import('./resources/ts/components/Pagination.vue')['default']
  const PasswordCheckList: typeof import('./resources/ts/components/PasswordCheckList.vue')['default']
  const RichTextEditor: typeof import('./resources/ts/components/RichTextEditor.vue')['default']
  const TableContent: typeof import('./resources/ts/components/table/components/table/TableContent.vue')['default']
  const TableFooter: typeof import('./resources/ts/components/table/components/table/footer/TableFooter.vue')['default']
  const ValidationError: typeof import('./resources/ts/components/ValidationError.vue')['default']
}