<script setup lang="ts">
import { ref } from 'vue'
import { router } from '@inertiajs/vue3'
import axios from 'axios'
import MessageBox from '@/components/MessageBox.vue'

const props = withDefaults(
  defineProps<{
    email: string
    password: string
    remember?: boolean
    authType?: 'totp' | 'email'
  }>(),
  {
    remember: false,
    authType: 'totp',
  },
)

const emit = defineEmits<{
  (e: 'back'): void
}>()

const verificationCode = ref('')
const loading = ref(false)
const resendLoading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

const verifyCode = async () => {
  if (!verificationCode.value || verificationCode.value.length < 6) {
    errorMessage.value = 'Please enter the full 6-digit verification code.'

    return
  }

  loading.value = true
  errorMessage.value = ''
  successMessage.value = ''

  try {
    const res = await axios.post('/crm/mfa/verify-code', {
      email: props.email,
      password: props.password,
      verification_code: verificationCode.value,
      remember: props.remember,
    })

    if (res.data.status === 'OK') {
      router.visit(res.data.redirect || '/crm/dashboard')
    } else {
      errorMessage.value = res.data.errors || 'Verification failed.'
    }
  } catch (err: any) {
    errorMessage.value = err.response?.data?.errors || err.response?.data?.message || 'Invalid verification code. Please try again.'
  } finally {
    loading.value = false
  }
}

const resendCode = async () => {
  resendLoading.value = true
  errorMessage.value = ''
  successMessage.value = ''
  try {
    const res = await axios.post('/crm/mfa/resend-code', {
      email: props.email,
      password: props.password,
    })

    if (res.data?.status === 'OK') {
      successMessage.value = res.data.message || 'A new 6-digit verification code has been sent to your email.'
    }
  } catch (err: any) {
    errorMessage.value = err.response?.data?.errors || err.response?.data?.message || 'Failed to resend code.'
  } finally {
    resendLoading.value = false
  }
}
</script>

<template>
  <div class="space-y-5">
    <div class="text-center mb-4">
      <div class="w-14 h-14 mx-auto mb-3 rounded-2xl bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 flex items-center justify-center text-2xl border border-emerald-100 dark:border-emerald-900/50 shadow-inner">
        <i
          v-if="authType === 'email'"
          class="ri-mail-check-line text-2xl"
        />
        <i
          v-else
          class="ri-shield-keyhole-line text-2xl"
        />
      </div>
      <h3 class="font-bold text-lg text-slate-900 dark:text-white">
        {{ authType === 'email' ? 'CRM Email Security Check' : 'CRM Authenticator MFA' }}
      </h3>
      <p class="text-xs text-slate-500 mt-1 max-w-xs mx-auto">
        <span v-if="authType === 'email'">
          A 6-digit security code has been sent to <b class="text-emerald-600 dark:text-emerald-400">{{ email }}</b>.
        </span>
        <span v-else>
          Enter the 6-digit code generated by your Authenticator app (Google Authenticator, Microsoft, etc.) to access the CRM Suite.
        </span>
      </p>
    </div>

    <MessageBox
      v-if="errorMessage"
      :message="errorMessage"
      type="error"
      @close="errorMessage = ''"
    />

    <MessageBox
      v-if="successMessage"
      :message="successMessage"
      type="success"
      @close="successMessage = ''"
    />

    <form
      class="space-y-4"
      @submit.prevent="verifyCode"
    >
      <div>
        <label class="block text-xs font-semibold uppercase tracking-wider text-slate-700 dark:text-slate-300 mb-1.5 text-center">
          6-Digit Verification Code
        </label>
        <div class="relative">
          <input
            v-model="verificationCode"
            type="text"
            inputmode="numeric"
            maxlength="6"
            pattern="[0-9]*"
            autocomplete="one-time-code"
            required
            autofocus
            placeholder="000000"
            class="w-full text-center tracking-[0.5em] text-2xl font-mono font-bold py-3 px-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 focus:ring-2 focus:ring-emerald-500 focus:outline-none transition-all"
          >
        </div>
      </div>

      <button
        type="submit"
        :disabled="loading"
        class="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-700 hover:from-emerald-700 hover:to-teal-800 text-white font-semibold text-sm shadow-lg shadow-emerald-500/25 disabled:opacity-50 transition-all flex items-center justify-center gap-2 cursor-pointer"
      >
        <i
          v-if="loading"
          class="ri-loader-4-line animate-spin text-lg"
        />
        <span>{{ loading ? 'Authenticating...' : 'Confirm & Access CRM' }}</span>
      </button>

      <div class="flex items-center justify-between pt-2">
        <button
          type="button"
          class="text-xs font-medium text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 flex items-center gap-1 cursor-pointer"
          @click="emit('back')"
        >
          <i class="ri-arrow-left-line" /> Back to CRM Login
        </button>

        <button
          v-if="authType === 'email'"
          type="button"
          :disabled="resendLoading"
          class="text-xs font-semibold text-emerald-600 dark:text-emerald-400 hover:underline disabled:opacity-50 flex items-center gap-1 cursor-pointer"
          @click="resendCode"
        >
          <i
            v-if="resendLoading"
            class="ri-loader-4-line animate-spin"
          />
          <i
            v-else
            class="ri-refresh-line"
          />
          <span>Resend Code</span>
        </button>
      </div>
    </form>
  </div>
</template>
