<?php

namespace App\DTOs\Cms;

use Illuminate\Database\Eloquent\Model;

readonly class SiteSettingDTO
{
    public function __construct(
        public ?int $id = null,
        public ?string $description = null,
        public ?string $mobile = null,
        public ?string $phone = null,
        public ?string $email = null,
        public ?string $support_email = null,
        public ?string $website = null,
        public ?string $address = null,
        public ?string $whatsapp = null,
        public ?string $viber = null,
        public ?string $pininterest = null,
        public ?string $tiktok = null,
        public ?string $linkedin = null,
        public ?string $instagram = null,
        public ?string $youtube = null,
        public ?string $twitter = null,
        public ?string $facebook = null,
        public ?string $copy_right_text = null,
        public ?string $cookie_content_text = null,
        public ?string $terms_condition = null,
        public ?string $zoom_link = null,
        public ?string $map_url = null,
        public ?string $tagline = null,
        public ?string $logo = null,
        public ?string $email_logo_image = null,
        public ?string $app_logo = null,
        public ?int $enable_cookies = 0,
        public ?string $fav_icon = null,
        public ?string $slogan = null,
        public ?string $login_bg_image = null,
        public ?string $login_bg_color = null,
        public ?string $primary_color = null,
        public ?string $secondary_color = null,
        public ?string $seo_title = null,
        public ?string $seo_keyword = null,
        public ?string $seo_description = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'] ?? null,
            description: $data['description'] ?? null,
            mobile: $data['mobile'] ?? null,
            phone: $data['phone'] ?? null,
            email: $data['email'] ?? null,
            support_email: $data['support_email'] ?? null,
            website: $data['website'] ?? null,
            address: $data['address'] ?? null,
            whatsapp: $data['whatsapp'] ?? null,
            viber: $data['viber'] ?? null,
            pininterest: $data['pininterest'] ?? null,
            tiktok: $data['tiktok'] ?? null,
            linkedin: $data['linkedin'] ?? null,
            instagram: $data['instagram'] ?? null,
            youtube: $data['youtube'] ?? null,
            twitter: $data['twitter'] ?? null,
            facebook: $data['facebook'] ?? null,
            copy_right_text: $data['copy_right_text'] ?? null,
            cookie_content_text: $data['cookie_content_text'] ?? null,
            terms_condition: $data['terms_condition'] ?? null,
            zoom_link: $data['zoom_link'] ?? null,
            map_url: $data['map_url'] ?? null,
            tagline: $data['tagline'] ?? null,
            logo: $data['logo'] ?? null,
            email_logo_image: $data['email_logo_image'] ?? null,
            app_logo: $data['app_logo'] ?? null,
            enable_cookies: isset($data['enable_cookies']) ? (int) $data['enable_cookies'] : 0,
            fav_icon: $data['fav_icon'] ?? null,
            slogan: $data['slogan'] ?? null,
            login_bg_image: $data['login_bg_image'] ?? null,
            login_bg_color: $data['login_bg_color'] ?? null,
            primary_color: $data['primary_color'] ?? null,
            secondary_color: $data['secondary_color'] ?? null,
            seo_title: $data['seo_title'] ?? null,
            seo_keyword: $data['seo_keyword'] ?? null,
            seo_description: $data['seo_description'] ?? null,
        );
    }

    public static function fromModel(Model $model): self
    {
        return new self(
            id: $model->id,
            description: $model->description,
            mobile: $model->mobile,
            phone: $model->phone,
            email: $model->email,
            support_email: $model->support_email,
            website: $model->website,
            address: $model->address,
            whatsapp: $model->whatsapp,
            viber: $model->viber,
            pininterest: $model->pininterest,
            tiktok: $model->tiktok,
            linkedin: $model->linkedin,
            instagram: $model->instagram,
            youtube: $model->youtube,
            twitter: $model->twitter,
            facebook: $model->facebook,
            copy_right_text: $model->copy_right_text,
            cookie_content_text: $model->cookie_content_text,
            terms_condition: $model->terms_condition,
            zoom_link: $model->zoom_link,
            map_url: $model->map_url,
            tagline: $model->tagline,
            logo: $model->logo,
            email_logo_image: $model->email_logo_image,
            app_logo: $model->app_logo,
            enable_cookies: (int) $model->enable_cookies,
            fav_icon: $model->fav_icon,
            slogan: $model->slogan,
            login_bg_image: $model->login_bg_image,
            login_bg_color: $model->login_bg_color,
            primary_color: $model->primary_color,
            secondary_color: $model->secondary_color,
            seo_title: $model->seo_title,
            seo_keyword: $model->seo_keyword,
            seo_description: $model->seo_description,
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'description' => $this->description,
            'mobile' => $this->mobile,
            'phone' => $this->phone,
            'email' => $this->email,
            'support_email' => $this->support_email,
            'website' => $this->website,
            'address' => $this->address,
            'whatsapp' => $this->whatsapp,
            'viber' => $this->viber,
            'pininterest' => $this->pininterest,
            'tiktok' => $this->tiktok,
            'linkedin' => $this->linkedin,
            'instagram' => $this->instagram,
            'youtube' => $this->youtube,
            'twitter' => $this->twitter,
            'facebook' => $this->facebook,
            'copy_right_text' => $this->copy_right_text,
            'cookie_content_text' => $this->cookie_content_text,
            'terms_condition' => $this->terms_condition,
            'zoom_link' => $this->zoom_link,
            'map_url' => $this->map_url,
            'tagline' => $this->tagline,
            'logo' => $this->logo,
            'email_logo_image' => $this->email_logo_image,
            'app_logo' => $this->app_logo,
            'enable_cookies' => $this->enable_cookies,
            'fav_icon' => $this->fav_icon,
            'slogan' => $this->slogan,
            'login_bg_image' => $this->login_bg_image,
            'login_bg_color' => $this->login_bg_color,
            'primary_color' => $this->primary_color,
            'secondary_color' => $this->secondary_color,
            'seo_title' => $this->seo_title,
            'seo_keyword' => $this->seo_keyword,
            'seo_description' => $this->seo_description,
        ], fn ($value) => $value !== null);
    }
}
